document.write('<link rel="stylesheet" href="./css/theme/index.css">')
document.write('<link rel="stylesheet" href="./js/layui/css/layui.css">')
document.write('<link rel="stylesheet" href="./css/index.css">')
document.write('<script src="./js/vue.js"></script>')
document.write('<script src="./js/element_ui.js"></script>')
document.write('<script src="./js/layui/layui.js"></script>')
document.write('<script src="./js/util.js"></script>')
document.write('<script src="./js/axios.js"></script>')
document.write('<script src="./js/qs.js"></script>')
document.write('<script src="./js/http.js"></script>')
document.write('<script src="./js/request.js"></script>')
document.write('<script src="./js/directive.js"></script>')
document.write('<script src="./js/mixin.js"></script>')
document.write('<script src="./component/collapse.js"></script>')
document.write('<script src="./component/control.js"></script>')
document.write('<script src="./component/tableList.js"></script>')

